### ISSUE TITLE
DimensionReduction UMAP algorithm not recognized

### ISSUE THREAD

**Issue by imoutsatsos** [NumbersInternational/flipDimensionReduction#24]
I have installed  **flipDimensionReduction R package v1.2.14** and when I try to use the UMAP algorithm I get the error "Algorithm not recognized" . I have also reviewed the source code here: https://github.com/Displayr/flipDimensionReduction/blob/master/R/dimensionreductionscatterplot.R and it appears that there is no logic for the UMAP algorithm.

Is this an oversight or did you drop support for the UMAP algorithm (which by the way I have used from your older package for many years successfully) . The package documentation still lists UMAP as one of the algorithm options.

Thank you for your contributions to this very important topic!

**Comment by mwmclean** [comment]
Yes, we did drop support for it in 52f7171. Sorry that the documentation was not updated to reflect this. We tested out UMAP around five years ago, but never ended up using it in our software/exposing it to our paying customers. You may want to create a fork, revert that commit, and install your fork to see if UMAP can still work for you.

**Comment by imoutsatsos** [comment]
Thank you for the feedback. Out of curiosity, was UMAP abandoned due to its complexity with the Python package requirement or did you find little use for it in your line of work? Do you find that t-SNE is sufficient or quasi-equivalent to UMAP? Nonetheless, I want you to know that I got much mileage out of your initial implementation and I'm very thankful for it!

**Comment by mwmclean** [comment]
Unfortunately, the engineer that tested out UMAP is no longer with our company and we didn't keep a record of his experiments. I can only assume that UMAP did not perform as well/better on our test data sets as t-SNE and hence, was abandoned.
